### ISSUE TITLE
Selenium Timeout

### ISSUE THREAD

**Issue by naterfute** [IOKernel/chess-bot#10]
When your opponent takes to long to move it will time out and then be unusable

Traceback (most recent call last):
  File "/home/kaleb/coding/python/chessfavorite/Sangatsu/sangatsu.py", line 25, in <module>
    main()
  File "/home/kaleb/coding/python/chessfavorite/Sangatsu/sangatsu.py", line 19, in main
    gm.play_game(driver, engine)
  File "/home/kaleb/coding/python/chessfavorite/Sangatsu/utils/game.py", line 48, in play_game
    move = detect_move(driver, move_number, turn)
  File "/home/kaleb/coding/python/chessfavorite/Sangatsu/utils/game.py", line 39, in detect_move
    move = WebDriverWait(driver, 60).until(
  File "/home/kaleb/coding/python/chessfavorite/.venv/lib64/python3.10/site-packages/selenium/webdriver/support/wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:280:16

**Comment by IOKernel** [comment]
changed timeout to 3 minutes
