### ISSUE TITLE
Can't Play bots

### ISSUE THREAD

**Issue by naterfute** [IOKernel/chess-bot#11]
Whenever you try to get into a bot game this happens:

Traceback (most recent call last):
  File "/home/kaleb/coding/python/chessfavorite/Sangatsu/sangatsu.py", line 25, in <module>
    main()
  File "/home/kaleb/coding/python/chessfavorite/Sangatsu/sangatsu.py", line 15, in main
    game_state = hp.detect_game(driver)
  File "/home/kaleb/coding/python/chessfavorite/Sangatsu/utils/helpers.py", line 102, in detect_game
    raise Exception('Could not find tabs!')
Exception: Could not find tabs!

**Comment by kusayuzayushko** [comment]
+1 for this

**Comment by IOKernel** [comment]
Fixed, got broken when they added the bot personalities.
Might have some bugs

**Comment by SolsticeSpectrum** [comment]
> Fixed, got broken when they added the bot personalities. Might have some bugs

Hardcoded redirect to either https://www.chess.com/play/computer or https://www.chess.com/play/online isn't good 
Maybe add a command parameter?
