### ISSUE TITLE
I'm getting this error.

### ISSUE THREAD

**Issue by somenormalguy7** [IOKernel/chess-bot#12]
I'm using windows 11

C:\Users\shamanth\Downloads\Sangatsu-master (1)\Sangatsu-master>python sangatsu.py
Traceback (most recent call last):
  File "C:\Users\shamanth\Downloads\Sangatsu-master (1)\Sangatsu-master\sangatsu.py", line 24, in <module>
    main()
  File "C:\Users\shamanth\Downloads\Sangatsu-master (1)\Sangatsu-master\sangatsu.py", line 11, in main
    driver = hp.start_driver(username, password)
  File "C:\Users\shamanth\Downloads\Sangatsu-master (1)\Sangatsu-master\utils\helpers.py", line 74, in start_driver
    driver = webdriver.Firefox(profile, executable_path=os.path.join(SCRIPT_DIR, 'bin', 'geckodriver'))
  File "C:\Users\shamanth\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 192, in __init__
    self.service.start()
  File "C:\Users\shamanth\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 90, in start
    self._start_process(self.path)
  File "C:\Users\shamanth\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 198, in _start_process
    self.process = subprocess.Popen(
  File "C:\Users\shamanth\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\shamanth\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher

**Comment by somenormalguy7** [comment]
solved firefox was not installed :)
