### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by ovhx** [IOKernel/chess-bot#18]
D:\Sangatsu-master>python sangatsu.py
Traceback (most recent call last):
  File "D:\AppFiles\Python3\Lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\site-packages\chess\engine.py", line 1429, in initialize
    return await self.communicate(UciInitializeCommand)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\site-packages\chess\engine.py", line 1094, in communicate
    return await command.result
           ^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Sangatsu-master\sangatsu.py", line 24, in <module>
    main()
  File "D:\Sangatsu-master\sangatsu.py", line 12, in main
    engine = gm.start_engine()
             ^^^^^^^^^^^^^^^^^
  File "D:\Sangatsu-master\utils\game.py", line 32, in start_engine
    engine = chess.engine.SimpleEngine.popen_uci(os.path.join(SCRIPT_DIR, 'bin', 'stockfish'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\site-packages\chess\engine.py", line 2861, in popen_uci
    return cls.popen(UciProtocol, command, timeout=timeout, debug=debug, setpgrp=setpgrp, **popen_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\site-packages\chess\engine.py", line 2853, in popen
    return run_in_background(background, name=f"{cls.__name__} (command={command!r})", debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\site-packages\chess\engine.py", line 201, in run_in_background
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\AppFiles\Python3\Lib\site-packages\chess\engine.py", line 195, in background
    asyncio.run(coroutine(future))
  File "D:\AppFiles\Python3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\AppFiles\Python3\Lib\site-packages\chess\engine.py", line 2845, in background
    await asyncio.wait_for(protocol.initialize(), timeout)
  File "D:\AppFiles\Python3\Lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError

**Comment by ovhx** [comment]
Nevermind, fixed by adding  ,timeout=60) in line 32
