### ISSUE TITLE
Fails on parsing error

### ISSUE THREAD

**Issue by Jorjote** [IOKernel/chess-bot#2]
I'm on Linux Mint, every time I play a game I get the following error after playing a couple of moves:
```
1 e4
0.014888286590576172
2 e5
0.014434337615966797
3 Cf3
0.00987553596496582
4 d5
0.008256196975708008
5 exd5
0.016583919525146484
6 f6
0.014503240585327148
7 Cc3
0.01816272735595703
8 Dxd5
error during pgn parsing
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.8/site-packages/chess/pgn.py", line 1555, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "/home/john/.local/lib/python3.8/site-packages/chess/pgn.py", line 938, in parse_san
    return board.parse_san(san)
  File "/home/john/.local/lib/python3.8/site-packages/chess/__init__.py", line 2832, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'xd5' in rnbqkbnr/ppp3pp/5p2/3Pp3/8/2P2P2/PP1P2PP/RNBQKBNR b KQkq - 0 4
0.007962226867675781
9 Cxd5
error during pgn parsing
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.8/site-packages/chess/pgn.py", line 1555, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "/home/john/.local/lib/python3.8/site-packages/chess/pgn.py", line 938, in parse_san
    return board.parse_san(san)
  File "/home/john/.local/lib/python3.8/site-packages/chess/__init__.py", line 2832, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'xd5' in rnbqkbnr/ppp3pp/5p2/3Pp3/8/2P2P2/PP1P2PP/RNBQKBNR b KQkq - 0 4
0.009389877319335938

```

At that point the hack stops working. I think it is because my pieces are named in spanish (Dxd5 instead of Qxd5)

**Comment by Jorjote** [comment]
Ok I solved it by changing my account language to english.
