### ISSUE TITLE
Exception if game lost by checkmate

### ISSUE THREAD

**Issue by kusayuzayushko** [IOKernel/chess-bot#4]
```
Are you ready to play? (y/n): 
Traceback (most recent call last):
  File "chess-bot.py", line 77, in play_game
    result = driver.find_element_by_class_name("white node game-result").text
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .white node game-result


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "chess-bot.py", line 163, in <module>
    main()
  File "chess-bot.py", line 159, in main
    play_game(driver, engine)
  File "chess-bot.py", line 87, in play_game
    best_move = get_best_move(engine, board, move)
  File "chess-bot.py", line 95, in get_best_move
    best_move = engine.play(board, chess.engine.Limit(depth=5))
  File "/usr/local/lib/python3.8/dist-packages/chess/engine.py", line 2759, in play
    return future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/dist-packages/chess/engine.py", line 1660, in play
    return await self.communicate(UciPlayCommand)
  File "/usr/local/lib/python3.8/dist-packages/chess/engine.py", line 1069, in communicate
    return await command.result
  File "/usr/local/lib/python3.8/dist-packages/chess/engine.py", line 1280, in _line_received
    self.line_received(engine, line)
  File "/usr/local/lib/python3.8/dist-packages/chess/engine.py", line 1597, in line_received
    self._bestmove(engine, line.split(" ", 1)[1])
  File "/usr/local/lib/python3.8/dist-packages/chess/engine.py", line 1616, in _bestmove
    best = _parse_uci_bestmove(engine.board, arg)
  File "/usr/local/lib/python3.8/dist-packages/chess/engine.py", line 1835, in _parse_uci_bestmove
    raise EngineError(err)
chess.engine.EngineError: invalid uci (use 0000 for null moves): 'a1a1'
```

**Comment by kusayuzayushko** [comment]
Update: doesn't matter if won or lost, actually - checkmate leads to the exact same error. 
Update2: a1a1 is returned when lc0 is forced to move when it's a draw or a checkmate (if you use lc0 instead of stockfish).

**Comment by IOKernel** [comment]
fixed in new version
