### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hodzzaa** [IOKernel/chess-bot#8]
I get this after 2nd move I make after game started!
I am on windows 10 64 bit

Game started!
Traceback (most recent call last):
  File "C:\Users\monta\Desktop\Sangatsu-master\sangatsu.py", line 24, in <module>
    main()
  File "C:\Users\monta\Desktop\Sangatsu-master\sangatsu.py", line 18, in main
    gm.play_game(driver, engine)
  File "C:\Users\monta\Desktop\Sangatsu-master\utils\game.py", line 54, in play_game
    board.push_san(move)
  File "C:\Users\monta\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\__init__.py", line 2845, in push_san
    move = self.parse_san(san)
  File "C:\Users\monta\AppData\Local\Programs\Python\Python39\lib\site-packages\chess\__init__.py", line 2832, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'xb4' in rnbqkbnr/pppp1ppp/8/4p3/1P2P3/8/P1PP1PPP/RNBQKBNR b KQkq - 0 2

**Comment by Hodzzaa** [comment]
fixed it by changing piece notation from figurine to text

**Comment by IOKernel** [comment]
In your chess.com preferences, change Piece Notation from Figurine to Text. Should work fine afterwards.
