### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by naterfute** [IOKernel/chess-bot#9]
Im running Fedora 37 

Traceback (most recent call last):
  File "/home/kaleb/coding/python/chess/Sangatsu/sangatsu.py", line 24, in <module>
    main()
  File "/home/kaleb/coding/python/chess/Sangatsu/sangatsu.py", line 18, in main
    gm.play_game(driver, engine)
  File "/home/kaleb/coding/python/chess/Sangatsu/utils/game.py", line 54, in play_game
    board.push_san(move)
  File "/home/kaleb/coding/python/chess/Sangatsu/chess/lib64/python3.10/site-packages/chess/__init__.py", line 3052, in push_san
    move = self.parse_san(san)
  File "/home/kaleb/coding/python/chess/Sangatsu/chess/lib64/python3.10/site-packages/chess/__init__.py", line 3039, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'b4' in rnbqkbnr/pp1p2pp/2p2p2/4p3/3PP3/2P2P2/PP4PP/RNBQKBNR b KQkq - 0 4

**Comment by IOKernel** [comment]
Try changing the piece notation from images to text in chess.com settings

**Comment by naterfute** [comment]
That Fixed it Thank you
